# Generated by Django 3.2 on 2021-05-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='itemfile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='ctx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.ctx', verbose_name='CTX'),
        ),
        migrations.AddField(
            model_name='item',
            name='variation',
            field=models.ManyToManyField(to='item.Variation', verbose_name='Variation'),
        ),
        migrations.AddField(
            model_name='item',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.vat', verbose_name='Vat'),
        ),
    ]
