# Generated by Django 3.2 on 2021-05-23 13:02

import _helpers.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('img', models.ImageField(blank=True, null=True, upload_to=_helpers.models.client_img_upload_path, verbose_name='User Image')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='User Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='User Phone Number')),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='Gender')),
                ('address', models.CharField(max_length=250, verbose_name='User Address')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='City name')),
                ('paying_method', models.IntegerField(choices=[(1, 'cash'), (2, 'installments')], default=1, verbose_name='Payment Method')),
                ('country', models.CharField(max_length=250, verbose_name='Country name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Register at')),
                ('active_til', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of deactive the client')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('taxes', models.BooleanField(default=False, verbose_name='Taxes')),
                ('cash', models.FloatField(blank=True, default=0.0, null=True, verbose_name='cash of account')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
