# Generated by Django 3.2 on 2021-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_taxes_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cash',
            field=models.PositiveBigIntegerField(blank=True, default=0.0, null=True, verbose_name='cash of account'),
        ),
        migrations.AlterField(
            model_name='client',
            name='taxes_rate',
            field=models.PositiveBigIntegerField(blank=True, default=0.0, null=True, verbose_name='Taxes Rate'),
        ),
    ]
