# Generated by Django 3.2 on 2021-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210603_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cash',
            field=models.PositiveBigIntegerField(blank=True, default=0.0, null=True, verbose_name='inital cash of account'),
        ),
    ]
