# Generated by Django 3.2 on 2021-06-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_cash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': (), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
