# Generated by Django 3.2 on 2021-06-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
