# Generated by Django 3.2 on 2021-05-23 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('item', '0002_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')], default=1, help_text='the transaction type', verbose_name='Payment transaction Type')),
                ('description', models.TextField(blank=True, help_text='the description of the transaction', null=True, verbose_name='Description')),
                ('amount', models.FloatField(help_text='amount to be paid', verbose_name='amount')),
                ('currency', models.IntegerField(choices=[(1, 'egp'), (2, 'usd'), (3, 'euro'), (4, 'rub')], help_text='currency of transaction', verbose_name='Currency')),
                ('issued_at', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Issued at')),
                ('type_tranasction', models.IntegerField(choices=[(1, 'Sales'), (2, 'Refund'), (3, 'Deposite')], default=1, help_text='transaction type', verbose_name='Transaction type')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Payment Type')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued at')),
                ('method', models.IntegerField(choices=[(1, 'cash'), (2, 'installments')], default=1, max_length=2, verbose_name='Payment method')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount Paid')),
                ('currency', models.IntegerField(choices=[(1, 'egp'), (2, 'usd'), (3, 'euro'), (4, 'rub')], verbose_name='Currency')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Paymentes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(default=0.0, max_length=150, verbose_name='Price')),
                ('supplier_price', models.FloatField(default=0.0, verbose_name='Supplier Price')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.discount', verbose_name='Discount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Transaction Items',
                'verbose_name_plural': 'Transaction Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentTransaction',
            fields=[
                ('paymenttransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymenttransaction')),
                ('items', models.ManyToManyField(through='payment.OrderItem', to='item.Item', verbose_name='Item of the transactions if there are any')),
                ('supplier', models.ForeignKey(help_text='to whom the transaction  is', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='supplier.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier payment transaction',
                'verbose_name_plural': 'Supplier payment transactions',
            },
            bases=('payment.paymenttransaction',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.supplierpaymenttransaction', verbose_name='  '),
        ),
        migrations.CreateModel(
            name='ClientPaymentTransaction',
            fields=[
                ('paymenttransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymenttransaction')),
                ('client', models.ForeignKey(help_text='to whom the transaction  is', on_delete=django.db.models.deletion.DO_NOTHING, to='client.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client payment transaction',
                'verbose_name_plural': 'Client payment transactions',
            },
            bases=('payment.paymenttransaction',),
        ),
    ]
