# Generated by Django 3.2 on 2021-05-23 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount to be paid', validators=[django.core.validators.MaxValueValidator(999999, 'max value is 999999'), django.core.validators.MinValueValidator(0, "can't be less than zero")], verbose_name='amount'),
        ),
    ]
