# Generated by Django 3.2 on 2021-05-23 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymenttransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount to be paid', validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
    ]
