# Generated by Django 3.2 on 2021-05-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenttransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount to be paid', validators=[django.core.validators.MinValueValidator], verbose_name='amount'),
        ),
    ]
