# Generated by Django 3.2 on 2021-05-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210523_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount to be paid', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='amount'),
        ),
    ]
