# Generated by Django 3.2 on 2021-05-23 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenttransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount to be paid', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999.0)], verbose_name='amount'),
        ),
    ]
