# Generated by Django 3.2 on 2021-05-30 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_country'),
        ('payment', '0006_alter_paymenttransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaymenttransaction',
            name='client',
            field=models.ForeignKey(help_text='to whom the transaction  is', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='client.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.IntegerField(choices=[(1, 'egp'), (2, 'usd'), (3, 'euro'), (4, 'rub')], default=1, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(help_text='amount', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999.0)], verbose_name='amount'),
        ),
    ]
