# Generated by Django 3.2 on 2021-05-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20210530_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.supplierpaymenttransaction', verbose_name='transaction'),
        ),
    ]
