# Generated by Django 3.2 on 2021-05-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_orderitem_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.paymenttype', verbose_name='Payment transaction Type'),
        ),
    ]
