# Generated by Django 3.2 on 2021-05-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_paymenttransaction_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='clientpaymenttransaction',
            name='payment_type',
            field=models.ForeignKey(default=1, limit_choices_to={'transaction_type': 2}, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.paymenttype', verbose_name='Payment transaction Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Supplier Transactions'), (2, 'Client Transactions')], default=1, verbose_name='Transaction type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpaymenttransaction',
            name='payment_type',
            field=models.ForeignKey(default=1, limit_choices_to={'transaction_type': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.paymenttype', verbose_name='Payment transaction Type'),
            preserve_default=False,
        ),
    ]
