# Generated by Django 3.2 on 2021-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20210531_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')], help_text='the transaction type', verbose_name='Payment transaction Type'),
        ),
    ]
