# Generated by Django 3.2 on 2021-06-03 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_paymenttransaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveBigIntegerField(default=0.0, max_length=150, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_price',
            field=models.PositiveBigIntegerField(default=0.0, verbose_name='Supplier Price'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveBigIntegerField(help_text='amount', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999.0)], verbose_name='amount'),
        ),
    ]
