# Generated by Django 3.2 on 2021-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20210603_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Payment Type'),
        ),
    ]
