# Generated by Django 3.2 on 2021-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_paymenttransactiontype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='file_transaction',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='File'),
        ),
    ]
