# Generated by Django 3.2 on 2021-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_paymenttransaction_file_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactiontype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Payment Type'),
        ),
    ]
