# Generated by Django 3.2 on 2021-06-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0007_alter_supplier_cash'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone number')),
                ('additional_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Additinol phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Addres')),
                ('openinig', models.TimeField(blank=True, null=True, verbose_name='Opening time')),
                ('closing', models.TimeField(blank=True, null=True, verbose_name='Opening time')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='area.area', verbose_name='Area')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.executive', verbose_name='Warehouse manager')),
            ],
        ),
    ]
