# Generated by Django 3.2 on 2021-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='en',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
