# Generated by Django 3.2 on 2021-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_rename_en_area_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area'},
        ),
    ]
