# Generated by Django 3.2 on 2021-06-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_administration_department_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_user.job', verbose_name='Job name'),
            preserve_default=False,
        ),
    ]
