# Generated by Django 3.2 on 2021-06-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_user.job', verbose_name='Job name'),
        ),
    ]
