# Generated by Django 3.2 on 2021-06-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210603_1253'),
        ('supplier', '0005_auto_20210603_1253'),
        ('app_user', '0007_closingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingperiod',
            name='delimter',
            field=models.CharField(default='debit', max_length=50, verbose_name='delimiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closingperiod',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peroid', to='client.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='closingperiod',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peroid', to='supplier.supplier', verbose_name='Supplier'),
        ),
    ]
