# Generated by Django 3.2 on 2021-06-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_auto_20210608_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='administration',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
    ]
