# Generated by Django 3.2 on 2021-06-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('app_user', '0009_auto_20210609_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='area.area', verbose_name='Area'),
            preserve_default=False,
        ),
    ]
