# Generated by Django 3.2 on 2021-06-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_alter_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app_user.department', verbose_name='Department'),
        ),
    ]
