# Generated by Django 3.2 on 2021-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_supplier_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cash',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='inital cash of account'),
        ),
    ]
